---
apiVersion: v1
kind: Secret
metadata:
  name: secret-secret
  namespace: default
type: Opaque
data:
  config.yaml: |
    c2V0dGluZzE6ICJ2YWx1ZTEiCnNldHRpbmcyOiAidmFsdWUyIgpzZXR0aW5nMzogInZhbHVlMyIK
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-deployment
  namespace: default
  labels:
    app: sandbox
    environment: test
    role: sandbox
    kubecaso.io: "enabled"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
        environment: test
        role: sandbox
        kubecaso.io: "enabled"
    spec:
      containers:
        - name: sandbox-container
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "test"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/config # Путь, где будет доступен Secret внутри контейнера
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: secret-secret # Название секрета