---
apiVersion: v1
kind: Secret
metadata:
  name: market-service-envs
  namespace: default
type: Opaque
data:
  DB_USER: ZGVmYXVsdF91c2Vy # base64-кодированное значение для пользователя
  DB_PASSWORD: cGFzc3dvcmQ= # base64-кодированное значение для пароля

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-deployment-2
  namespace: default
  labels:
    app: sandbox
    environment: test
    role: sandbox
    kubecaso.io: "enabled"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
        environment: test
        role: sandbox
        kubecaso.io: "enabled"
    spec:
      containers:
        - name: sandbox-container
          image: nginx:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: market-service-envs