apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-config
  namespace: default
data:
  config.yaml: |
    setting1: "valusde1"
    setting2: "value2"
    setting3: "value3"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-deployment
  namespace: default
  labels:
    app: sandbox
    environment: test
    role: sandbox
    kubecaso.io: "enabled"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
        environment: test
        role: sandbox
        kubecaso.io: "enabled"
    spec:
      containers:
        - name: sandbox-container
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "test"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config # Путь, где будет доступен ConfigMap внутри контейнера
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: configmap-config